/**
 * Builds the demo question paper: CBSE Class X Mathematics (Basic) 2020.
 *
 * The wording is transcribed from the printed questions in the supplied
 * Oswaal Topper's Answers document, so this paper and that answer sheet are
 * the same exam - which is the whole point. The source only exists as one
 * dense two-column page; this reflows it onto five readable pages so the
 * extractor sees a normal paper and every question gets a usable region.
 *
 * Text is plain ASCII: the helper writes Helvetica with the standard
 * encoding, where a sqrt or angle glyph would come out as garbage.
 *
 *   npx tsx tools/make-demo-question-paper.ts fixtures/demo-question-paper.pdf
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { A4_PORTRAIT } from '../tests/fixtures/documents';
import { makePdfWithLines } from '../tests/fixtures/text-pdf';

const PAGES: string[][] = [
  [
    'CBSE CLASS X - MATHEMATICS (BASIC)',
    'Delhi / Outside Delhi',
    '',
    'Maximum Time: 3 hours                                   Maximum Marks: 80',
    '',
    'General Instructions:',
    '(i)   This question paper comprises four sections - A, B, C and D.',
    '(ii)  All questions are compulsory.',
    '(iii) Section A: Question numbers 1 to 20 carry 1 mark each.',
    '(iv)  Section B: Question numbers 21 to 26 carry 2 marks each.',
    '(v)   Section C: Question numbers 27 to 34 carry 3 marks each.',
    '(vi)  Use of calculators is not permitted.',
    '',
    'SECTION A',
    '',
    'Question numbers 1 to 20 carry 1 mark each.',
    'Choose the correct option in question numbers 1 to 10.',
    '',
    '1. Given that HCF (156, 78) = 78, LCM (156, 78) is    [1]',
    '   (A) 156     (B) 78     (C) 156 x 78     (D) 156 x 2',
    '',
    '2. Sides of two similar triangles are in the ratio 4 : 9. Areas of these',
    '   triangles are in the ratio    [1]',
    '   (A) 4 : 9     (B) 2 : 3     (C) 81 : 16     (D) 16 : 81',
    '',
    '3. The distance between the points (-1, -3) and (5, -2) is    [1]',
    '   (A) sqrt(61) units   (B) sqrt(37) units   (C) 5 units   (D) sqrt(17) units',
    '',
    '4. The discriminant of the quadratic equation 2x^2 - 4x + 3 = 0 is    [1]',
    '   (A) -8     (B) 10     (C) 8     (D) 2 sqrt(2)',
    '   OR',
    '   Roots of the quadratic equation 2x^2 - 4x + 3 = 0 are',
    '   (A) real and equal   (B) real and distinct   (C) not real   (D) real',
  ],
  [
    '5. Numbers of zeroes of the polynomial p(x) shown in Figure-1 are    [1]',
    '   (A) 3     (B) 2     (C) 1     (D) 0',
    '',
    '6. A dice is thrown once. The probability of getting an odd number is    [1]',
    '   (A) 1     (B) 1/2     (C) 4/6     (D) 2/6',
    '',
    '7. The value of k for which the equations 3x - y + 8 = 0 and',
    '   6x + ky = -16 represent coincident lines, is    [1]',
    '   (A) -1/2     (B) 1/2     (C) 2     (D) -2',
    '',
    '8. If sin A = cos A, 0 <= A <= 90 degrees, then the angle A is equal to    [1]',
    '   (A) 30 degrees   (B) 60 degrees   (C) 0 degrees   (D) 45 degrees',
    '',
    '9. The second term from the end of the A.P. 5, 8, 11, ..., 47 is    [1]',
    '   (A) 50     (B) 45     (C) 44     (D) 41',
    '',
    '10. Total surface area of a solid hemisphere of radius r is    [1]',
    '    (A) 3 pi r^2     (B) 2 pi r^2     (C) 4 pi r^2     (D) (2/3) pi r^2',
    '',
    'Fill in the blanks in question numbers 11 to 14.',
    '',
    '11. The roots of the equation x^2 + bx + c = 0 are equal if ________.    [1]',
    '',
    '12. The mid-point of the line segment joining the points (-3, -3) and',
    '    (3, 3) is ________.    [1]',
    '',
    '13. The lengths of the tangents drawn from an external point to a circle',
    '    are ________.    [1]',
    '',
    '14. In the quadratic polynomial x^2 - 16, the sum of the zeroes is ________.    [1]',
  ],
  [
    'Answer the following question numbers 15 to 20.',
    '',
    '15. Write the 26th term of the A.P. 7, 4, 1, -2, ...    [1]',
    '',
    '16. Find the coordinates of the point on the x-axis which divides the line',
    '    segment joining the points (2, 3) and (5, -6) in the ratio 1 : 2.    [1]',
    '',
    '17. The angle of elevation of the top of a tower AB from a point C on the',
    '    ground, which is 60 m away from the foot of the tower, is 30 degrees,',
    '    as shown in Figure-2. Find the height of the tower.    [1]',
    '',
    '18. In Figure-3, find the length of the tangent PQ drawn from the point P',
    '    to a circle with centre at O, given that OP = 12 cm and OQ = 5 cm.    [1]',
    '',
    '19. Evaluate: sin 30 degrees + cos 60 degrees.    [1]',
    '',
    '20. Write the empirical relationship between mean, median and mode.    [1]',
    '',
    'SECTION B',
    '',
    'Question numbers 21 to 26 carry 2 marks each.',
    '',
    '21. A cylindrical bucket, 32 cm high and with radius of base 14 cm, is',
    '    filled completely with sand. Find the volume of the sand.',
    '    Use pi = 22/7.    [2]',
    '',
    '22. In Figure-4, triangle ABC and triangle XYZ are shown. If AB = 3.8 cm,',
    '    AC = 3 sqrt(3) cm, BC = 6 cm, XY = 6 sqrt(3) cm, XZ = 7.6 cm,',
    '    YZ = 12 cm and angle A = 65 degrees, angle B = 70 degrees, then find',
    '    the value of angle Y.    [2]',
    '    OR',
    '    If the areas of two similar triangles are equal, show that they are',
    '    congruent.',
  ],
  [
    '23. Find the sum of the first 15 multiples of 8.    [2]',
    '',
    '24. Show that every positive even integer is of the form 2q, and that',
    '    every positive odd integer is of the form 2q + 1, where q is some',
    '    integer.    [2]',
    '',
    '25. A card is drawn at random from a well-shuffled pack of 52 playing',
    '    cards. Find the probability that the card drawn is neither a king',
    '    nor a queen.    [2]',
    '',
    '26. The following table shows the ages of the patients admitted in a',
    '    hospital during a year:    [2]',
    '',
    '    Age (in years) : 5-15, 15-25, 25-35, 35-45, 45-55, 55-65',
    '    Number of patients : 60, 110, 210, 230, 150, 50',
    '',
    '    Find the mode of the distribution.',
    '',
    'SECTION C',
    '',
    'Question numbers 27 to 34 carry 3 marks each.',
    '',
    '27. Seema has a 10 m x 10 m kitchen garden attached to her kitchen. She',
    '    divides it into a 10 x 10 grid and wants to grow some vegetables and',
    '    herbs used in the kitchen. She puts some soil and manure in that and',
    '    sows a green chilly plant at A, a coriander plant at B and a tomato',
    '    plant at C. Her friend Kusum visited the garden and praised the plants',
    '    grown there. She pointed out that they seem to be in a straight line.',
    '    See the diagram carefully and answer:',
    '',
    '    27 (a) Write the coordinates of the points A, B and C taking the',
    '           10 x 10 grid as coordinate axes.    [1]',
    '',
    '    27 (b) By distance formula or some other formula, check whether the',
    '           points A, B and C are collinear.    [2]',
  ],
  [
    '28. In Figure-5, a circle is inscribed in a triangle ABC touching BC, CA',
    '    and AB at P, Q and R respectively. If AB = 10 cm, AQ = 7 cm and',
    '    CQ = 5 cm, find the length of BC.    [3]',
    '    OR',
    '    In Figure-6, two tangents TP and TQ are drawn to a circle with centre',
    '    O from an external point T. Prove that angle PTQ = 2 angle OPQ.',
    '',
    '29. Prove that sqrt(2) is an irrational number.    [3]',
    '',
    '30. Draw a line segment of length 7.6 cm and divide it in the ratio',
    '    5 : 8. Measure the two parts.    [3]',
    '',
    '31. The mean of the following frequency distribution is 25. Find the',
    '    value of p.    [3]',
    '',
    '    Class : 0-10, 10-20, 20-30, 30-40, 40-50',
    '    Frequency : 5, 18, 15, p, 6',
    '',
    '32. Solve for x and y :  2x + 3y = 11  and  2x - 4y = -24.',
    '    Hence find the value of m for which y = mx + 3.    [3]',
    '',
    '33. Prove that the tangent at any point of a circle is perpendicular to',
    '    the radius through the point of contact.    [3]',
    '',
    '34. A container shaped like a right circular cylinder having diameter',
    '    12 cm and height 15 cm is full of ice cream. Find the number of cones',
    '    that can be filled if each cone has radius 3 cm and height 12 cm.    [3]',
    '',
    '- END OF QUESTION PAPER -',
  ],
];

const out = process.argv[2] ?? 'fixtures/demo-question-paper.pdf';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, makePdfWithLines(PAGES.map((lines) => ({ ...A4_PORTRAIT, lines }))));
console.log(`demo question paper written: ${out} (${PAGES.length} pages)`);
